# ===== Stage 1: Build =====
FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline -B
COPY src ./src
RUN mvn clean package -DskipTests

# ===== Stage 2: Run =====
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/target/actify-0.0.1-SNAPSHOT.jar app.jar

ENV PORT=80
EXPOSE 80

ENTRYPOINT ["sh", "-c", "java -jar app.jar --server.port=${PORT}"]